#task 1

In [ ]:
import numpy as np
arr = np.array([55, 89, 76, 65, 48, 92])
arr_plus_5 = arr + 5
max_score = arr_plus_5.max()
print(arr.ndim)
print(arr.dtype) 
print(arr)
print(arr_plus_5)
print(max_score)


1
int64
[55 89 76 65 48 92]
[60 94 81 70 53 97]
97


#task 2

In [8]:
import numpy as np

matrix = np.random.randint(10, 101, size=(5, 4))
print(matrix.shape)

wednesday = matrix[2,2]
print(wednesday)

high = matrix[matrix > 80]
print(high)

(5, 4)
27
[95 89 88 83 81 82 94]
